import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'EN' | 'UA' | 'RU';

interface LanguageCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageCtx>({
  lang: 'EN',
  setLang: () => {},
  t: (k) => k,
});

export const useLanguage = () => useContext(LanguageContext);

// Deep get from nested object by dot-path
const get = (obj: Record<string, unknown>, path: string): string => {
  const parts = path.split('.');
  let cur: unknown = obj;
  for (const p of parts) {
    if (cur == null || typeof cur !== 'object') return path;
    cur = (cur as Record<string, unknown>)[p];
  }
  return typeof cur === 'string' ? cur : path;
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>('EN');
  const t = (key: string) => get(translations[lang] as Record<string, unknown>, key);
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Lang, Record<string, unknown>> = {
  EN: {
    header: {
      services: 'Services',
      work: 'Work',
      about: 'About',
      contact: 'Contact',
      bookCall: 'Book a call',
    },
    hero: {
      eyebrow: 'Booking Q3 · 2 spots open',
      sig: 'EST. 2019 · WARSAW / KYIV',
      line1: 'Ads that',
      italic: 'actually',
      line2: 'return',
      accent: 'revenue',
      sub: "I'm Mariana — a performance marketer who builds full-funnel growth systems for founders tired of agencies that report impressions instead of sales.",
      ctaPrimary: 'Free consultation',
      ctaSecondary: 'View case studies',
      scroll: 'scroll',
      roas: 'Avg ROAS · 90d',
      roasDelta: '↑ 212% vs pre-engagement',
      leads: 'Leads / mo',
      leadsDelta: '14 active clients',
      managed: 'Managed in 2025',
      managedDelta: 'Jan–Dec',
      reply: 'Reply time',
      replyValue: '< 2h',
      replyDelta: 'EN / UA / RU',
    },
    services: {
      sectionNum: '/ 01 · Services',
      title: 'Five disciplines.\nOne operator running all of them.',
      desc: "You don't need another agency juggling accounts between juniors. You need one senior who can see the whole funnel — from ad to landing page to CRM — and fix whichever part is losing you money this week.",
      learnMore: 'Learn more',
      meta: { name: 'Meta Ads', sub: 'Facebook & Instagram', desc: 'Full-funnel campaigns engineered for purchase, lead, and conversation objectives — with creative testing baked in.' },
      google: { name: 'Google Ads', sub: 'Search, PMax, Display', desc: 'High-intent traffic, ruthless negative-keyword hygiene, and PMax asset groups that actually convert.' },
      web: { name: 'Website Development', sub: 'Landing pages & sites', desc: 'Conversion-first pages built for speed, clarity, and CRM integration — not just pretty.' },
      smm: { name: 'Social Media Management', sub: 'Content + community', desc: 'Editorial calendars, short-form video, and community growth that supports paid acquisition.' },
      seo: { name: 'SEO', sub: 'Organic growth', desc: 'Technical audits, content systems, and topic clusters that compound for 12+ months.' },
    },
    cases: {
      sectionNum: '/ 02 · Selected work',
      title: "Numbers that survived\nthe finance team.",
      desc: 'Every case below is measured against actual revenue — not CTR, not vanity reach. Pick a niche close to yours; results are usually directionally similar.',
    },
    testimonials: {
      sectionNum: '/ 03 · Clients',
      title: "What founders say\nafter the first quarter.",
      desc: "These aren't marketplace reviews. They're the founders who stuck around for year two.",
    },
    about: {
      sectionNum: '/ 04 · About',
      badge: 'Available for new projects',
      title: "Seven years inside other people's ad accounts — and I still find broken conversion events on day one.",
      p1: "I started in-house at a DTC brand that was hemorrhaging budget on lookalikes that didn't convert. After rebuilding the account from scratch and scaling to €1.2M/year, founders started asking me to do the same for them. I've been solo ever since.",
      p2: "I work with 10–14 clients at a time, never more. Every account has my hands in it — not a junior's, not an AI summary. If your numbers aren't moving in 60 days, you don't pay for month three.",
      yearsVal: '7y',
      yearsLabel: 'Performance marketing',
      managedVal: '€2.4M',
      managedLabel: 'Managed in 2025',
      brandsVal: '42',
      brandsLabel: 'Brands scaled',
      cta: 'Work with me',
    },
    contact: {
      sectionNum: '/ 05 · Contact',
      title: 'Fastest answer is\non Telegram.',
      desc: 'Usually back within two hours during working days. For anything urgent, Telegram or WhatsApp.',
      telegramName: 'Telegram · fastest',
      whatsappName: 'WhatsApp',
      whatsappHandle: '+48 — on request',
      instagramName: 'Instagram',
      facebookName: 'Facebook',
      emailName: 'Email',
      nameLabel: 'Your name',
      namePlaceholder: 'Oksana Kovalenko',
      businessLabel: 'Business',
      businessPlaceholder: 'Company + niche',
      budgetLabel: 'Monthly ad budget',
      budgetDefault: 'Select a range',
      budget1: 'Under €2k / month',
      budget2: '€2k–5k / month',
      budget3: '€5k–15k / month',
      budget4: '€15k–50k / month',
      budget5: '€50k+ / month',
      budget6: 'Not sure yet',
      contactMethodLabel: 'Preferred contact method',
      messageLabel: 'What do you want to grow?',
      messagePlaceholder: "A sentence or two is enough — what the business does, what you've tried, what 'success' looks like in 90 days.",
      submitBtn: 'Send & book a free 30-min call',
      formFoot: 'No auto-responders. No CRM drip. Real human reply.',
      successMsg: "Got it — I'll reply within 2 hours.",
    },
    footer: {
      tagline: 'Solo performance marketer for founders who want fewer dashboards and more revenue.',
      services: 'Services',
      studio: 'Studio',
      elsewhere: 'Elsewhere',
      caseStudies: 'Case studies',
      clients: 'Clients',
      copyright: '© 2026 Mariana Leus · Performance Marketing',
      location: 'Warsaw · Kyiv · Remote worldwide',
      backToTop: 'Back to top ↑',
    },
    privacy: {
      title: 'Privacy Policy',
      updated: 'Last updated: April 2026',
      intro: 'This Privacy Policy explains how Mariana Leus collects, uses, and protects your personal information.',
      s1Title: '1. Information We Collect',
      s1: 'We collect information you provide directly: name, business details, and any other information submitted through the contact form on this website.',
      s2Title: '2. How We Use Your Information',
      s2: 'Your information is used solely to respond to your inquiry, schedule consultations, and provide the services you requested. We do not sell or share your data with third parties.',
      s3Title: '3. Data Storage',
      s3: 'Form submissions are sent directly via email. No data is stored on our servers beyond what is necessary to respond to your inquiry.',
      s4Title: '4. Cookies',
      s4: 'This website may use minimal technical cookies for analytics purposes. You can disable cookies in your browser settings at any time.',
      s5Title: '5. Contact',
      s5: 'For any questions regarding this privacy policy, contact us at marianaleus8@gmail.com.',
    },
    servicesPage: {
      crumb: 'Services',
      heroTitle1: 'Five disciplines.',
      heroItalic: 'One',
      heroTitle2: 'P&L.',
      heroLede: "Every retainer is structured so the cost of working with me is paid back by month two. No dashboards you don't understand, no agency theatre — just the one or two levers that move your numbers.",
      processNum: '/ How we work',
      processTitle: 'Four phases.\nNo surprises.',
      processDesc: "The shape of every engagement. Weeks are approximate; your team and brand will bend the schedule — I'll tell you how before we start.",
      faqNum: '/ FAQ',
      faqTitle: 'Questions founders ask\nin the first 10 minutes.',
      faqDesc: "Can't find yours? Send it over via Telegram or email — I reply within 2 hours during business hours.",
      ctaTitle: 'Ready to see what your\nactual ROAS should be?',
      ctaBookBtn: 'Book a free audit',
      ctaTelegramBtn: 'Message on Telegram',
    },
    aboutPage: {
      crumb: 'About',
      heroTitle1: "Seven years of watching",
      heroItalic: "other people's",
      heroTitle2: "ad accounts,",
      heroTitle3: "so you don't",
      heroUnderline: 'have to.',
      photoCaption: 'Warsaw · 2025 · 14-client cap',
      introLabel: '/ Introduction',
      intro1: "I started in-house at a skincare brand that was hemorrhaging budget on lookalikes that didn't convert. After rebuilding the account from scratch and scaling it to €1.2M in annual revenue, founders started asking me to do the same for them. I've been solo ever since — and I've kept it that way on purpose.",
      intro2: "Today I run a quiet, boring practice: 10–14 clients at a time, flat monthly retainers, no junior staff, no account managers, no sales funnel dressed up as a dashboard. If you're reading this page, the only person between you and your campaigns is me.",
      intro3: "Performance marketing rewards the patient and the specific. Most of what agencies sell as 'strategy' is a slideshow. The actual work is unglamorous: writing better ads, rebuilding tracking that never worked, killing audiences that never converted, and telling founders honestly when their product isn't ready to scale.",
      timelineNum: '/ Trajectory',
      timelineTitle: 'How I got here.',
      timelineDesc: 'Edited-down version. Full CV on request — but trajectory matters less than the shape of the practice now.',
      principlesNum: '/ Principles',
      principlesTitle: "Six things I won't bend on.",
      principlesDesc: "If any of these feel like friction, I'm probably not the right marketer for you — and that's fine. I'll recommend someone who is.",
      toolkitNum: '/ Toolkit',
      toolkitTitle: "What's in the stack.",
      toolkitDesc: "Tools are disposable. I care about the thinking, not the logos — but here's what I actually use day-to-day.",
      quote: "The edge isn't in the auction. It's in the ad.",
      quoteSource: '— Working belief, repeated weekly',
      ctaTitle1: 'Want to see what',
      ctaTitle2: 'working together',
      ctaTitle3: 'would',
      ctaItalic: 'actually',
      ctaTitle4: 'look like?',
      ctaBook: 'Book a 30-min call',
      ctaServices: 'See services',
    },
  },
  UA: {
    header: {
      services: 'Послуги',
      work: 'Роботи',
      about: 'Про мене',
      contact: 'Контакт',
      bookCall: 'Забронювати дзвінок',
    },
    hero: {
      eyebrow: 'Запис на Q3 · 2 вільних місця',
      sig: 'З 2019 · ВАРШАВА / КИЇВ',
      line1: 'Реклама, яка',
      italic: 'справді',
      line2: 'приносить',
      accent: 'дохід',
      sub: 'Я Маріана — performance-маркетолог, яка будує full-funnel системи зростання для засновників, втомлених від агентств, що звітують охопленням замість продажів.',
      ctaPrimary: 'Безкоштовна консультація',
      ctaSecondary: 'Переглянути кейси',
      scroll: 'гортати',
      roas: 'Середній ROAS · 90д',
      roasDelta: '↑ 212% до старту',
      leads: 'Ліди / міс',
      leadsDelta: '14 активних клієнтів',
      managed: 'Під управлінням 2025',
      managedDelta: 'Січ–Груд',
      reply: 'Час відповіді',
      replyValue: '< 2г',
      replyDelta: 'EN / UA / RU',
    },
    services: {
      sectionNum: '/ 01 · Послуги',
      title: "П'ять напрямків.\nОдин оператор для всіх.",
      desc: "Вам не потрібне ще одне агентство, де джуніори ведуть рахунки по черзі. Вам потрібен один старший фахівець, який бачить всю воронку — від реклами до лендингу і CRM — і виправляє те, що цього тижня забирає гроші.",
      learnMore: 'Дізнатись більше',
      meta: { name: 'Meta Ads', sub: 'Facebook & Instagram', desc: 'Повноворонкові кампанії для закупівель, лідів і конверсій — з системним тестуванням креативів.' },
      google: { name: 'Google Ads', sub: 'Пошук, PMax, Display', desc: "Висококонвертуючий трафік, жорстка гігієна мінус-слів і PMax-групи, що справді конвертують." },
      web: { name: 'Розробка сайтів', sub: 'Лендінги та сайти', desc: 'Сторінки, орієнтовані на конверсію: швидкі, зрозумілі, з інтеграцією CRM — не просто красиві.' },
      smm: { name: 'Управління соцмережами', sub: 'Контент + спільнота', desc: 'Редакційні календарі, короткі відео та розвиток спільноти для підтримки платної реклами.' },
      seo: { name: 'SEO', sub: 'Органічне зростання', desc: 'Технічні аудити, контент-системи та тематичні кластери з накопичувальним ефектом на 12+ місяців.' },
    },
    cases: {
      sectionNum: '/ 02 · Вибрані роботи',
      title: "Цифри, які пережили\nперевірку фінансистів.",
      desc: 'Кожен кейс нижче виміряний реальним доходом — не CTR, не охопленням. Виберіть нішу, близьку до вашої; результати зазвичай схожі.',
    },
    testimonials: {
      sectionNum: '/ 03 · Клієнти',
      title: "Що кажуть засновники\nпісля першого кварталу.",
      desc: "Це не відгуки з маркетплейсу. Це засновники, які залишилися на другий рік.",
    },
    about: {
      sectionNum: '/ 04 · Про мене',
      badge: 'Відкрита для нових проєктів',
      title: "Сім років у чужих рекламних кабінетах — і досі знаходжу зламані події конверсії з першого дня.",
      p1: "Я починала інхаус у DTC-бренді, який спалював бюджет на неефективні lookalike-аудиторії. Після повного перебудування акаунту і масштабування до €1.2M/рік засновники почали просити повторити те саме для них. З тих пір я працюю самостійно.",
      p2: "Я веду 10–14 клієнтів одночасно, не більше. Кожен акаунт — в моїх руках, без джуніорів, без AI-резюме. Якщо ваші показники не ростуть за 60 днів — ви не платите за третій місяць.",
      yearsVal: '7р',
      yearsLabel: 'Performance-маркетинг',
      managedVal: '€2.4M',
      managedLabel: 'Під управлінням 2025',
      brandsVal: '42',
      brandsLabel: 'Масштабованих брендів',
      cta: 'Співпрацювати зі мною',
    },
    contact: {
      sectionNum: '/ 05 · Контакт',
      title: 'Найшвидша відповідь —\nу Telegram.',
      desc: 'Зазвичай відповідаю протягом двох годин у робочий час. Для термінових питань — Telegram або WhatsApp.',
      telegramName: 'Telegram · найшвидше',
      whatsappName: 'WhatsApp',
      whatsappHandle: '+48 — за запитом',
      instagramName: 'Instagram',
      facebookName: 'Facebook',
      emailName: 'Email',
      nameLabel: "Ваше ім'я",
      namePlaceholder: 'Оксана Коваленко',
      businessLabel: 'Бізнес',
      businessPlaceholder: 'Компанія + ніша',
      budgetLabel: 'Щомісячний рекламний бюджет',
      budgetDefault: 'Оберіть діапазон',
      budget1: 'До €2k / місяць',
      budget2: '€2k–5k / місяць',
      budget3: '€5k–15k / місяць',
      budget4: '€15k–50k / місяць',
      budget5: '€50k+ / місяць',
      budget6: 'Ще не визначився',
      contactMethodLabel: 'Зручний спосіб звʼязку',
      messageLabel: 'Що ви хочете розвинути?',
      messagePlaceholder: "Кілька речень — чим займається бізнес, що вже пробували, як виглядає 'успіх' через 90 днів.",
      submitBtn: 'Надіслати та забронювати 30-хв дзвінок',
      formFoot: 'Без автовідповідачів. Без CRM-розсилок. Реальна людська відповідь.',
      successMsg: 'Отримала — відповім протягом 2 годин.',
    },
    footer: {
      tagline: 'Performance-маркетолог-одинак для засновників, які хочуть менше дашбордів і більше доходу.',
      services: 'Послуги',
      studio: 'Студія',
      elsewhere: 'Контакти',
      caseStudies: 'Кейси',
      clients: 'Клієнти',
      copyright: '© 2026 Mariana Leus · Performance Marketing',
      location: 'Варшава · Київ · Дистанційно',
      backToTop: 'Нагору ↑',
    },
    privacy: {
      title: 'Політика конфіденційності',
      updated: 'Оновлено: квітень 2026',
      intro: 'Ця Політика конфіденційності пояснює, як Mariana Leus збирає, використовує та захищає ваші персональні дані.',
      s1Title: '1. Яку інформацію ми збираємо',
      s1: "Ми збираємо інформацію, яку ви надаєте безпосередньо: ім'я, деталі бізнесу та будь-яку іншу інформацію, надіслану через контактну форму.",
      s2Title: '2. Як ми використовуємо вашу інформацію',
      s2: 'Ваша інформація використовується виключно для відповіді на ваш запит, планування консультацій та надання послуг. Ми не продаємо і не передаємо ваші дані третім особам.',
      s3Title: '3. Зберігання даних',
      s3: 'Форми надсилаються напряму електронною поштою. Дані не зберігаються на наших серверах.',
      s4Title: '4. Файли cookie',
      s4: 'Сайт може використовувати мінімальні технічні cookie для аналітики. Ви можете вимкнути cookie в налаштуваннях браузера.',
      s5Title: '5. Контакт',
      s5: 'З питань щодо цієї політики звертайтеся: marianaleus8@gmail.com.',
    },
    servicesPage: {
      crumb: 'Послуги',
      heroTitle1: "П'ять напрямків.",
      heroItalic: 'Один',
      heroTitle2: 'P&L.',
      heroLede: "Кожен ретейнер структурований так, що вартість роботи зі мною окупається до другого місяця. Без дашбордів, які ви не розумієте, без театру агентства — лише один-два важелі, що рухають ваші цифри.",
      processNum: '/ Як ми працюємо',
      processTitle: 'Чотири фази.\nБез сюрпризів.',
      processDesc: 'Так виглядає кожна співпраця. Тижні приблизні; ваша команда та бренд скоригують графік — я розповім про це до старту.',
      faqNum: '/ FAQ',
      faqTitle: 'Питання засновників\nза перші 10 хвилин.',
      faqDesc: 'Не знайшли своє? Напишіть у Telegram або email — відповідаю протягом 2 годин у робочий час.',
      ctaTitle: 'Готові дізнатись, яким\nмає бути ваш ROAS?',
      ctaBookBtn: 'Замовити безкоштовний аудит',
      ctaTelegramBtn: 'Написати у Telegram',
    },
    aboutPage: {
      crumb: 'Про мене',
      heroTitle1: "Сім років у чужих",
      heroItalic: "рекламних",
      heroTitle2: "кабінетах,",
      heroTitle3: "щоб вам не довелося",
      heroUnderline: 'робити це самим.',
      photoCaption: 'Варшава · 2025 · ліміт 14 клієнтів',
      introLabel: '/ Вступ',
      intro1: "Я починала інхаус у косметичному бренді, який спалював бюджет на lookalike-аудиторії, що не конвертували. Після повного перебудування акаунту і масштабування до €1.2M річного доходу засновники почали просити повторити те саме для них. З тих пір я працюю самостійно — і навмисне залишаю все саме так.",
      intro2: "Сьогодні я веду тихий, скромний бізнес: 10–14 клієнтів одночасно, фіксовані щомісячні ретейнери, без молодших співробітників, без менеджерів по роботі з клієнтами. Якщо ви читаєте цю сторінку, між вами та вашими кампаніями — лише я.",
      intro3: "Performance-маркетинг винагороджує терплячих і конкретних. Більшість того, що агентства продають як 'стратегію' — це презентація. Справжня робота — непривабливa: писати кращу рекламу, перебудовувати трекінг, вбивати аудиторії, що ніколи не конвертували, і чесно говорити засновникам, коли їх продукт не готовий до масштабування.",
      timelineNum: '/ Шлях',
      timelineTitle: 'Як я сюди потрапила.',
      timelineDesc: 'Скорочена версія. Повне резюме за запитом.',
      principlesNum: '/ Принципи',
      principlesTitle: 'Шість речей, від яких я не відступлю.',
      principlesDesc: "Якщо будь-який з них здається незручним — я, мабуть, не той маркетолог для вас, і це нормально. Порекомендую того, хто підійде.",
      toolkitNum: '/ Інструменти',
      toolkitTitle: 'Що в стеку.',
      toolkitDesc: 'Інструменти — замінні. Мене цікавить мислення, а не логотипи — але ось що я справді використовую щодня.',
      quote: 'Перевага не в аукціоні. Вона в рекламі.',
      quoteSource: '— Робоче переконання, яке повторюю щотижня',
      ctaTitle1: 'Хочете побачити,',
      ctaTitle2: 'як виглядала б',
      ctaTitle3: 'наша',
      ctaItalic: 'спільна',
      ctaTitle4: 'робота?',
      ctaBook: 'Забронювати 30-хв дзвінок',
      ctaServices: 'Переглянути послуги',
    },
  },
  RU: {
    header: {
      services: 'Услуги',
      work: 'Работы',
      about: 'Обо мне',
      contact: 'Контакт',
      bookCall: 'Записаться на звонок',
    },
    hero: {
      eyebrow: 'Запись на Q3 · 2 свободных места',
      sig: 'С 2019 · ВАРШАВА / КИЕВ',
      line1: 'Реклама, которая',
      italic: 'действительно',
      line2: 'приносит',
      accent: 'доход',
      sub: 'Я Марьяна — performance-маркетолог, которая строит full-funnel системы роста для основателей, устав ших от агентств, отчитывающихся охватом вместо продаж.',
      ctaPrimary: 'Бесплатная консультация',
      ctaSecondary: 'Смотреть кейсы',
      scroll: 'листать',
      roas: 'Средний ROAS · 90д',
      roasDelta: '↑ 212% до старта',
      leads: 'Лидов / мес',
      leadsDelta: '14 активных клиентов',
      managed: 'Под управлением 2025',
      managedDelta: 'Янв–Дек',
      reply: 'Время ответа',
      replyValue: '< 2ч',
      replyDelta: 'EN / UA / RU',
    },
    services: {
      sectionNum: '/ 01 · Услуги',
      title: 'Пять направлений.\nОдин оператор для всех.',
      desc: 'Вам не нужно ещё одно агентство, где джуниоры ведут аккаунты по очереди. Вам нужен один старший специалист, который видит всю воронку — от рекламы до лендинга и CRM — и исправляет то, что на этой неделе съедает ваши деньги.',
      learnMore: 'Узнать больше',
      meta: { name: 'Meta Ads', sub: 'Facebook & Instagram', desc: 'Полноворонковые кампании для покупок, лидов и конверсий — с системным тестированием креативов.' },
      google: { name: 'Google Ads', sub: 'Поиск, PMax, Display', desc: 'Высококонвертируемый трафик, жёсткая гигиена минус-слов и PMax-группы, которые действительно конвертируют.' },
      web: { name: 'Разработка сайтов', sub: 'Лендинги и сайты', desc: 'Страницы, ориентированные на конверсию: быстрые, понятные, с интеграцией CRM — не просто красивые.' },
      smm: { name: 'Управление соцсетями', sub: 'Контент + сообщество', desc: 'Редакционные календари, короткие видео и рост сообщества для поддержки платной рекламы.' },
      seo: { name: 'SEO', sub: 'Органический рост', desc: 'Технические аудиты, контент-системы и тематические кластеры с накопительным эффектом на 12+ месяцев.' },
    },
    cases: {
      sectionNum: '/ 02 · Избранные работы',
      title: "Цифры, которые пережили\nпроверку финансистов.",
      desc: 'Каждый кейс ниже измерен реальным доходом — не CTR, не охватом. Выберите нишу, близкую к вашей; результаты обычно схожи.',
    },
    testimonials: {
      sectionNum: '/ 03 · Клиенты',
      title: "Что говорят основатели\nпосле первого квартала.",
      desc: 'Это не отзывы с маркетплейса. Это основатели, которые остались на второй год.',
    },
    about: {
      sectionNum: '/ 04 · Обо мне',
      badge: 'Открыта для новых проектов',
      title: "Семь лет в чужих рекламных кабинетах — и до сих пор нахожу сломанные события конверсии с первого дня.",
      p1: "Я начинала инхаус в DTC-бренде, который сжигал бюджет на неэффективные lookalike-аудитории. После полного перестроения аккаунта и масштабирования до €1.2M/год основатели начали просить повторить то же самое для них. С тех пор я работаю самостоятельно.",
      p2: "Я веду 10–14 клиентов одновременно, не больше. Каждый аккаунт — в моих руках, без джуниоров, без AI-резюме. Если ваши показатели не растут за 60 дней — вы не платите за третий месяц.",
      yearsVal: '7л',
      yearsLabel: 'Performance-маркетинг',
      managedVal: '€2.4M',
      managedLabel: 'Под управлением 2025',
      brandsVal: '42',
      brandsLabel: 'Масштабированных брендов',
      cta: 'Работать со мной',
    },
    contact: {
      sectionNum: '/ 05 · Контакт',
      title: 'Быстрее всего —\nв Telegram.',
      desc: 'Обычно отвечаю в течение двух часов в рабочее время. Для срочного — Telegram или WhatsApp.',
      telegramName: 'Telegram · быстрее всего',
      whatsappName: 'WhatsApp',
      whatsappHandle: '+48 — по запросу',
      instagramName: 'Instagram',
      facebookName: 'Facebook',
      emailName: 'Email',
      nameLabel: 'Ваше имя',
      namePlaceholder: 'Оксана Коваленко',
      businessLabel: 'Бизнес',
      businessPlaceholder: 'Компания + ниша',
      budgetLabel: 'Ежемесячный рекламный бюджет',
      budgetDefault: 'Выберите диапазон',
      budget1: 'До €2k / месяц',
      budget2: '€2k–5k / месяц',
      budget3: '€5k–15k / месяц',
      budget4: '€15k–50k / месяц',
      budget5: '€50k+ / месяц',
      budget6: 'Пока не определился',
      contactMethodLabel: 'Удобный способ связи',
      messageLabel: 'Что вы хотите развить?',
      messagePlaceholder: "Пара предложений — чем занимается бизнес, что уже пробовали, как выглядит 'успех' через 90 дней.",
      submitBtn: 'Отправить и забронировать 30-мин звонок',
      formFoot: 'Без автоответчиков. Без CRM-рассылок. Живой ответ человека.',
      successMsg: 'Получила — отвечу в течение 2 часов.',
    },
    footer: {
      tagline: 'Performance-маркетолог-одиночка для основателей, которые хотят меньше дашбордов и больше дохода.',
      services: 'Услуги',
      studio: 'Студия',
      elsewhere: 'Контакты',
      caseStudies: 'Кейсы',
      clients: 'Клиенты',
      copyright: '© 2026 Mariana Leus · Performance Marketing',
      location: 'Варшава · Киев · Удалённо',
      backToTop: 'Наверх ↑',
    },
    privacy: {
      title: 'Политика конфиденциальности',
      updated: 'Обновлено: апрель 2026',
      intro: 'Эта Политика конфиденциальности объясняет, как Mariana Leus собирает, использует и защищает ваши персональные данные.',
      s1Title: '1. Какую информацию мы собираем',
      s1: 'Мы собираем информацию, которую вы предоставляете напрямую: имя, данные о бизнесе и любую другую информацию, отправленную через контактную форму.',
      s2Title: '2. Как мы используем вашу информацию',
      s2: 'Ваша информация используется исключительно для ответа на ваш запрос, планирования консультаций и оказания услуг. Мы не продаём и не передаём ваши данные третьим лицам.',
      s3Title: '3. Хранение данных',
      s3: 'Формы отправляются напрямую по электронной почте. Данные не хранятся на наших серверах.',
      s4Title: '4. Файлы cookie',
      s4: 'Сайт может использовать минимальные технические cookie для аналитики. Вы можете отключить cookie в настройках браузера.',
      s5Title: '5. Контакт',
      s5: 'По вопросам этой политики: marianaleus8@gmail.com.',
    },
    servicesPage: {
      crumb: 'Услуги',
      heroTitle1: 'Пять направлений.',
      heroItalic: 'Один',
      heroTitle2: 'P&L.',
      heroLede: 'Каждый ретейнер структурирован так, что стоимость работы со мной окупается ко второму месяцу. Без дашбордов, которые вы не понимаете, без театра агентства — только один-два рычага, которые двигают ваши цифры.',
      processNum: '/ Как мы работаем',
      processTitle: 'Четыре фазы.\nБез сюрпризов.',
      processDesc: 'Так выглядит каждое сотрудничество. Недели приблизительные; ваша команда и бренд скорректируют график — я расскажу об этом до старта.',
      faqNum: '/ FAQ',
      faqTitle: 'Вопросы основателей\nза первые 10 минут.',
      faqDesc: 'Не нашли свой? Напишите в Telegram или email — отвечаю в течение 2 часов в рабочее время.',
      ctaTitle: 'Готовы узнать, каким\ndолжен быть ваш ROAS?',
      ctaBookBtn: 'Заказать бесплатный аудит',
      ctaTelegramBtn: 'Написать в Telegram',
    },
    aboutPage: {
      crumb: 'Обо мне',
      heroTitle1: "Семь лет в чужих",
      heroItalic: "рекламных",
      heroTitle2: "кабинетах,",
      heroTitle3: "чтобы вам не пришлось",
      heroUnderline: 'делать это самим.',
      photoCaption: 'Варшава · 2025 · лимит 14 клиентов',
      introLabel: '/ Введение',
      intro1: "Я начинала инхаус в косметическом бренде, который сжигал бюджет на lookalike-аудитории, не конвертировавшие. После полного перестроения аккаунта и масштабирования до €1.2M годового дохода основатели начали просить повторить то же самое для них. С тех пор я работаю самостоятельно — и намеренно оставляю всё именно так.",
      intro2: "Сегодня я веду тихую, скромную практику: 10–14 клиентов одновременно, фиксированные ежемесячные ретейнеры, без младшего персонала, без аккаунт-менеджеров. Если вы читаете эту страницу, между вами и вашими кампаниями — только я.",
      intro3: "Performance-маркетинг награждает терпеливых и конкретных. Большинство того, что агентства продают как 'стратегию' — это презентация. Настоящая работа непривлекательна: писать лучшую рекламу, перестраивать трекинг, убивать аудитории, которые никогда не конвертировали, и честно говорить основателям, когда их продукт не готов к масштабированию.",
      timelineNum: '/ Траектория',
      timelineTitle: 'Как я сюда попала.',
      timelineDesc: 'Сокращённая версия. Полное CV по запросу.',
      principlesNum: '/ Принципы',
      principlesTitle: 'Шесть вещей, от которых я не отступлю.',
      principlesDesc: 'Если любой из них кажется неудобным — я, вероятно, не тот маркетолог для вас, и это нормально. Порекомендую того, кто подойдёт.',
      toolkitNum: '/ Инструменты',
      toolkitTitle: 'Что в стеке.',
      toolkitDesc: 'Инструменты — заменимы. Меня интересует мышление, а не логотипы — но вот что я действительно использую ежедневно.',
      quote: 'Преимущество не в аукционе. Оно в рекламе.',
      quoteSource: '— Рабочее убеждение, которое повторяю каждую неделю',
      ctaTitle1: 'Хотите увидеть,',
      ctaTitle2: 'как выглядела бы',
      ctaTitle3: 'наша',
      ctaItalic: 'совместная',
      ctaTitle4: 'работа?',
      ctaBook: 'Забронировать 30-мин звонок',
      ctaServices: 'Смотреть услуги',
    },
  },
};
